name = "Eizel and Zacky's Modpack"
author = "EdwardTheWatzo, PoolloverNathan, community"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07fcdf3e052643dcec13a0fdf91baac71d56b27ed66fdd5f379515372eb8d8f0"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
