name = "Eizel and Zacky's Modpack"
author = "EdwardTheWatzo, PoolloverNathan, community"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87e53bdf08cd5796ac6d9372a1443e629e7074286390590702bbd4d7288c8480"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
