name = "Eizel and Zacky's Modpack"
author = "EdwardTheWatzo, PoolloverNathan, community"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c69a035906baedce79c7c77469ea05ebe5b9781e7eac79011820dcdb91e9f62"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
