name = "Eizel and Zacky's Modpack"
author = "EdwardTheWatzo, PoolloverNathan, community"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acd078f8a1c9f2e8190eb868344456516d7bd36841b8b7a6a03d659fc3288919"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
