name = "Eizel and Zacky's Modpack"
author = "EdwardTheWatzo, PoolloverNathan, community"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b585978c8fc446d0c3a3561d77dabce92ba3d20aa691fc4ade01811947ca6084"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
