name = "Eizel and Zacky's Modpack"
author = "EdwardTheWatzo, PoolloverNathan, community"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15b5d886aa7fe3fe71b56d38d49459c1a3612d7ae5ca8428dcdfec4b67baaed8"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
