name = "Eizel and Zacky's Modpack"
author = "EdwardTheWatzo, PoolloverNathan, community"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e249243eb8ecb2cd643f94d0cee808cc0d71c581197f68c9a2ef417e7297f91b"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
