name = "Eizel and Zacky's Modpack"
author = "EdwardTheWatzo, PoolloverNathan, community"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5226c0d66777ddcc8f77d9e5c89f50c9a6428740e7be4ca6db74a6c799da05d"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
