name = "Eizel and Zacky's Modpack"
author = "EdwardTheWatzo, PoolloverNathan, community"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "811be28a3281f5710993ff6c2266b3e973a954d97b21b58b8148d0354c3bde50"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
